# Generated by Django 4.2 on 2024-09-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graffiti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headset',
            name='vr_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
