# Generated by Django 4.1.5 on 2023-02-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='field',
            field=models.CharField(choices=[('BC', 'BCC'), ('CC', 'CC'), ('TO', 'TO')], default='BC', max_length=2),
        ),
    ]
