# Generated by Django 4.1.5 on 2023-02-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members_can_email_all',
            field=models.BooleanField(default=False),
        ),
    ]
