# Generated by Django 4.1.5 on 2023-02-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_group_members_can_email_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupuserthru',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
