# Generated by Django 4.1.5 on 2023-02-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_domainnames_group_safe_domains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='safe_domains',
        ),
        migrations.RemoveField(
            model_name='groupuserthru',
            name='status',
        ),
        migrations.AddField(
            model_name='groupuserthru',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='DomainNames',
        ),
    ]
