# Generated by Django 4.1.5 on 2023-02-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_remove_group_safe_domains_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupuserthru',
            name='enabled',
        ),
        migrations.AddField(
            model_name='groupuserthru',
            name='status',
            field=models.CharField(choices=[('WA', 'Waiting for admins to OK'), ('AC', 'Active member'), ('BA', 'Banned')], default='WA', max_length=2),
        ),
        migrations.AddField(
            model_name='group',
            name='safe_domains',
            field=models.ManyToManyField(to='group.domainnames'),
        ),
    ]
