# Generated by Django 4.2 on 2023-12-16 10:19

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BA', 'Bar chart'), ('PI', 'Pie chart'), ('HI', 'Histogram')], default='BA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(help_text='Short title, which is used to generate the URL for the survey', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.JSONField(default=dict)),
                ('text', models.TextField()),
                ('graph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dv', to='livesurvey.graph')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='livesurvey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('data', models.JSONField(default=dict)),
                ('form', models.CharField(max_length=64)),
                ('session_id', models.CharField(max_length=32)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livesurvey.survey')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='graph',
            name='iv1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iv1', to='livesurvey.question'),
        ),
        migrations.AddField(
            model_name='graph',
            name='iv2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iv2', to='livesurvey.question'),
        ),
    ]
